// include/js/interactiveMarker.vue
<template>
	<div></div>
</template>

<script>
// inspired from https://github.com/hatchbed/vue-ros3djs
import * as ROS3D from 'ros3d';

export default {
	name: 'ros-interactive-marker',
	props: {
		topic: {
			type: String,
			require: true,
		},
	},
	mounted() {
		console.log(this.$parent);
		this.imClient = new ROS3D.InteractiveMarkerClient({
			ros: this.$parent.ros,
			tfClient: this.$parent.tfClient,
			topic: this.topic,
			camera: this.$parent.viewer.camera,
			rootObject: this.$parent.viewer.selectableObjects,
		});
	},
	beforeDestroy() {
		this.imClient.unsubscribe();
	},
};
</script>

// include/js/InteractiveMarker.tsx
// inspired from https://github.com/hatchbed/vue-ros3djs
import * as ROS3D from 'ros3d'
import {onCleanup, createMemo} from 'solid-js'

import type * as ROSLIB from 'roslib'

export function InteractiveMarker(props: {
    topic: string
    ros: ROSLIB.Ros
    tfClient: ROSLIB.TFClient
    viewer: ROS3D.Viewer
}) {
    // This updates the imClient if props change.
    const imClient = createMemo<ROS3D.InteractiveMarkerClient | undefined>(previousImClient => {
        if (previousImClient) previousImClient.unsubscribe()

        return new ROS3D.InteractiveMarkerClient({
            ros: props.ros,
            tfClient: props.tfClient,
            topic: props.topic,
            camera: props.viewer.camera,
            rootObject: props.viewer.selectableObjects,
        })
    })

    onCleanup(() => {
        imClient().unsubscribe()
    })

    return null
}
